### ISSUE TITLE
CurrencyRate class seems to be out of sync (missing fromCurrency, useless transactionCurrency)

### ISSUE THREAD

**Issue by ahfeel** [netsuitephp/netsuite-php#158]
**Describe the bug**
According to the WSDL, the CurrencyRate object should be:
```
<complexType name="CurrencyRate">
<sequence>
<element name="baseCurrency" type="platformCore:RecordRef" minOccurs="1" maxOccurs="1"/>
<element name="fromCurrency" type="platformCore:RecordRef" minOccurs="1" maxOccurs="1"/>
<element name="exchangeRate" type="xsd:double" minOccurs="1" maxOccurs="1"/>
<element name="effectiveDate" type="xsd:dateTime" minOccurs="1" maxOccurs="1"/>
</sequence>
</complexType>
```
Unfortunately the correspond PHP Class is missing the fromCurrency attribute and has a "useless" transactionCurrency attribute.
This leads to the following warning when doing a `getCurrencyRate` request:
`PHP Deprecated:  Creation of dynamic property NetSuite\Classes\CurrencyRate::$fromCurrency is deprecated in /.../vendor/ryanwinchester/netsuite-php/src/NetSuiteClient.php on line 198`

**How To Reproduce**
```
        $request = new GetCurrencyRateRequest();
        $request->currencyRateFilter = new CurrencyRateFilter();
        $request->currencyRateFilter->baseCurrency = RecordRefFactory::fromInternalId(
            RecordType::currency,
            1
        );
        $request->currencyRateFilter->fromCurrency = RecordRefFactory::fromInternalId(
            RecordType::currency,
            2
        );
        $request->currencyRateFilter->effectiveDate = $effectiveDate;

        $response = $this->service->getCurrencyRate($request);
```

**Additional context**
Tried with all SOAP versions from 2020_1 to 2023_1

**Comment by jrebs** [comment]
This project is just a repackaging of the php toolkit distributed by NetSuite. The `CurrencyRate` class as you are seeing it is exactly how it is delivered by NetSuite. I think you're looking at an incorrect version of WSDL.

Directly out of the toolkit, this is the `CurrencyRate` class that gets extracted:

```php
// From toolkit/NetSuiteService.php
class CurrencyRate extends Record {
	/**
	 * @access public
	 * @var RecordRef
	 */
	public $baseCurrency;
	/**
	 * @access public
	 * @var RecordRef
	 */
	public $transactionCurrency;
	/**
	 * @access public
	 * @var float
	 */
	public $exchangeRate;
	/**
	 * @access public
	 * @var dateTime
	 */
	public $effectiveDate;
	/**
	 * @access public
	 * @var RecordRef
	 */
	public $currencyRateType;
	/**
	 * @access public
	 * @var string
	 */
	public $internalId;

	static $paramtypesmap = array(
		"baseCurrency" => "RecordRef",
		"transactionCurrency" => "RecordRef",
		"exchangeRate" => "float",
		"effectiveDate" => "dateTime",
		"currencyRateType" => "RecordRef",
		"internalId" => "string",
	);
}
```

According to the web services schema browser, this is correct as of 2023_1: 

https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2023_1/schema/record/currencyrate.html 

And finally, the current WSDL I'm seeing (https://webservices.netsuite.com/xsd/lists/v2023_1_0/accounting.xsd) shows:

```xml
<element name="currencyRate" type="listAcct:CurrencyRate"/>
<complexType name="CurrencyRate">
<complexContent>
<extension base="platformCore:Record">
<sequence>
<element name="baseCurrency" type="platformCore:RecordRef" minOccurs="0"/>
<element name="transactionCurrency" type="platformCore:RecordRef" minOccurs="0"/>
<element name="exchangeRate" type="xsd:double" minOccurs="0"/>
<element name="effectiveDate" type="xsd:dateTime" minOccurs="0"/>
<element name="currencyRateType" type="platformCore:RecordRef" minOccurs="0"/>
</sequence>
<!--  primary record internalId  -->
<attribute name="internalId" type="xsd:string"/>
</extension>
</complexContent>
</complexType>
```

**Comment by ahfeel** [comment]
Thanks for your quick answer @jrebs.

Have a look at this : https://webservices.netsuite.com/xsd/platform/v2023_1_0/core.xsd

You can see that there's a CurrencyRate type there that has the description I sent above, and this is the object that is received when doing a GetCurrencyRateRequest. Test it yourself, you'll get the warning.

So I think there's a problem somewhere and the issue should not be closed :)

**Comment by jrebs** [comment]
That may be true, but if it is true, then it's not an issue with this package (which is what I was trying to impart in the first paragraph of my reply and which is outlined in this package's readme), it's an issue that needs to be taken up with NetSuite. Their documentation and their toolkit and some of the WSDL all corroborate that the php classes are correct. As a general rule, we stick to repackaging the NetSuite classes and do not make inferrences about what might/could be done differently at that low level. If something is actually wrong with the NetSuite distribution, as has been the case in the past, we wait until it gets fixed upstream and then that fix will naturally make it into this package. In the past, it has been the case that just staying on a slightly older version of the PHP package has been sufficient, but since you've said that even 2020 is incorrect, I would certainly suggest you reach out to NetSuite about it. The simple fact of the matter is that if you used NetSuite's own toolkit and documentation, you'd be in exactly the same situation, so the fix is not one that belongs here.
