### ISSUE TITLE
PHP Fatal error:  Cannot redeclare array_is_associative()

### ISSUE THREAD

**Issue by syed-netable** [netsuitephp/netsuite-php#72]
Hi, We are getting this error

PHP Fatal error:  Cannot redeclare array_is_associative() (previously declared in /var/www/html/vendor/weew/helpers-array/src/array.php:328) in /var/www/html/vendor/ryanwinchester/netsuite-php/src/includes/functions.php on line 29

**Comment by jrebs** [comment]
This isn't really a bug. It looks like you're using two separate third party libraries which happen to declare functions with the same name. It looks like the `weew` library does a check on the function existence before it declares, so if you loaded the netsuite toolkit before loading that other library, in theory you shouldn't have the conflict (though since the functions are not identical there could be potentially side effects - you'd want to test it out first).

In a future version we could make changes to the functions in this toolkit to make them more declarative, such as putting them into a namespace or just prefixing them, but that will not be happening immediately so I'd suggest for quick resolution you juggle the order in which you're loading the modules to see if you can move past the conflict.

**Comment by syed-netable** [comment]
Hi Jrebs, Thank you for your quick replay

We haven't declared any third party library. It comes by default in Magento2.3 platform
It didn't exist in Magento2.2 edition

**Comment by jrebs** [comment]
Well, I'm afraid I can't really diagnose your issue directly as I don't know anything about this platform you're using. All I know is what is shown in your error message. There's a helpers-array library being included from the vendor 'weew' and it is declaring a function in src/array.php on line 328 which is later redeclared by netsuite toolkit. This is an unfortunate problem with global functions. I'll make some time in the next week to work out a solution, either putting our functions into a namespace or just renaming them to use package prefixes.

**Comment by neclimdul** [comment]
I think this demonstrates the problem. Should be an easy fix, the functions behave the same so just wrapping it in a `function_exists` should handle it.

https://github.com/neclimdul/netsuite-php-test

**Comment by emog** [comment]
I think all these functions should be a static methods of new class. This will resolve any conflicts with other packages.

**Comment by neclimdul** [comment]
That seems a bit overkill. if you want to namespace the function just namespace the function. static comes with its own problems.
