### ISSUE TITLE
xml files created on each call

### ISSUE THREAD

**Issue by Richi2293** [netsuitephp/netsuite-php#83]
Basically, for each call you make with this library, two xml files are always created.
But how do you manage with these files?
Is there a way to automatically clean them after a few days?

Thanks

**Comment by jrebs** [comment]
> Basically, for each call you make with this library, two xml files are always created.

Yes, one for the outgoing request, one for the returned response. This is also how each request gets logged in the NetSuite interface in the web services log.

> But how do you manage with these files?

I only enable them when I'm debugging an issue. Once I no longer need them, I disable logging on my side since the NetSuite logs are usually sufficient. I also store logs of all my NetSuite interactions in our database using our own custom methods so that basic information about all our calls are tracked (record type, action, internalId, success/fail status, execution time, etc).

> Is there a way to automatically clean them after a few days?

There sure is, but it's outside the scope of this library. You could write a simple shell script that runs as a cron task nightly and deletes log files based on their creation timestamp or by parsing the filenames for the date and time they were made.
