### ISSUE TITLE
How do I search for the latest Fulfillment items?

### ISSUE THREAD

**Issue by Richi2293** [netsuitephp/netsuite-php#84]
Hi,

I am trying to do a search that results in the latest (last 5 days) shipments with shipStatus "Shipped" but I am not succeeding.

This is my code:

```
$NetSuiteHelper->service->setSearchPreferences(false, 20);

$search = new TransactionSearchBasic();

$searchForData = new SearchDateField();
$searchForData->operator = "on";
$searchForData->predefinedSearchValue = "fiveDaysAgo";


$search->tranDate = $searchForData;

$search->shipStatus = "Shipped";

$request = new SearchRequest();
$request->searchRecord = $search;

$searchResponse = $NetSuiteHelper->service->search($request);

if (!$searchResponse->searchResult->status->isSuccess) {
    echo "SEARCH ERROR";
} else {
    $result = $searchResponse->searchResult;
    $count = $result->totalRecords;
    $records = $result->recordList;
    $response = array (
        'success' => true,
        'count' => $count,
        'records' => $records
    );
    echo json_encode($response);
}
```

I checked this class:
"vendor/ryanwinchester/netsuite-php/src/Classes/TransactionSearchBasic.php"
And the shipStatus field is not present, what can I do?

This is the documentation:
https://system.netsuite.com/help/helpcenter/en_US/srbrowser/Browser2020_1/schema/record/itemfulfillment.html

The shipStatus exists in the documentation.

Thanks

**Comment by jrebs** [comment]
`shipStatus` is a property of the `ItemFulfillment` class, just like you pointed out is in the documentation. You are trying to use it as a property of the `TransactionSearchBasic` class, so it obviously doesn't work there.

Separately, I'd recommend using class constants in place of literal strings in your code. The values you're using might be correct now, but they could change in a future release and you won't want all your code to break. Specifically I am talking about changing stuff like this:

```php
$searchForData->operator = "on";
$searchForData->predefinedSearchValue = "fiveDaysAgo";
$search->shipStatus = "Shipped";
```

to:

```php
$searchForData->operator = SearchDateFieldOperator::on;
$searchForData->predefinedSearchValue = SearchDate::fiveDaysAgo;
$search->shipStatus = ItemFulfillmentShipStatus::_shipped;
```

If you continue to have problems after fixing the way you're trying to target the shipStatus field, I recommend googling some examples of searches. There are lots of threads on stackoverflow that address how to do this stuff which I used when figuring out my own usage a few years ago. You don't specifically need to find examples using this same library. Generally the examples from any language can be used to figure out where you're going wrong because they are all building web services requests to do the same stuff, just using slightly different syntax.

Closing because not an issue with the library.
